### ISSUE TITLE
emmmm小白提几个小问题

### ISSUE THREAD

**Issue by 9tail123** [w-digital-scanner/w9scan#11]
首先向大佬问好Y(^_^)Y 
第一个问题是对网站的错误页面识别能力不太好，很多网站跑起来一大串漏洞提示，size都一样的（￣～￣）
其次是w9scan跑起来后貌似会运行update.py

**Comment by 9tail123** [comment]
额，没写完就不小心点出去了。。。补充下。
w9scan跑起来后过一会github就不能访问，貌似被封了ip，停止脚本后就恢复正常，没耐心学过python，不晓得是不是脚本出了问题

**Comment by boy-hack** [comment]
1.方便提供URL测试吗？
2.不会自动更新 只有输入 --update 才会更新
3.封IP可能是访问过于频繁，出口宽带受阻

**Comment by 9tail123** [comment]
url是www.gzs.cn，刚才用baidu.com也有一样效果。刚才可能是github恰巧来大姨妈了，站长工具ping也全部超时，朋友那里也是一样打不开╮(￣⊿￣)╭我还研究了半天这个脚本是不是有dos作用
