### ISSUE TITLE
Error: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by Imanfeng** [w-digital-scanner/w9scan#13]
choose all plugins
but it stop at 400 code...

[*] 80 => [www]; Ver => [('Server', 'Tengine')]
81 => [www]; Ver => [('Server', 'Microsoft-HTTPAPI/2.0')]
443 => [ssl]; Ver => [('Server', 'Tengine')]
Error: HTTP Error 400: Bad Request
^C
^C^C^C^C^C^C
...

**Comment by boy-hack** [comment]
Ignore it
