### ISSUE TITLE
-u参数有问题

### ISSUE THREAD

**Issue by 9tail123** [w-digital-scanner/w9scan#18]
-u参数指定url后脚本仍然需要input url，如果直接回车会退出脚本....这个-u参数和没用一样，还有--guide参数也是好像和python w9scan.py一样效果

**Comment by boy-hack** [comment]
python w9scan.py -u "https://blog.hacking8.com/" -p emlog 指定插件扫描网站
python w9scan.py -u "@1.txt" -p emlog 指定插件批量扫描网站

-u 是指定插件扫描而设定的
