### ISSUE TITLE
关于不指定插件无法批量

### ISSUE THREAD

**Issue by d4wner** [w-digital-scanner/w9scan#28]
老兄这个不指定插件无法批量扫描URL么？是怕并发太大？

**Comment by boy-hack** [comment]
向导模式中输入URL时可以输入类似@1.txt,代表批量扫描1.txt内的URL

**Comment by d4wner** [comment]
额，我指定可以w9scan批量，但是我批量后没有指定插件，就运行不起来。

**Comment by d4wner** [comment]
还有个新问题，git主看看，能解决可以试着解决下，不能就算了，我就不开新issue了：
`python w9scan.py -u https://www.baidu.com`

好像是无效的，如果不指定-p插件，每次都会进入引导模式，还需要输入url。

这里好像又回到了先前的问题，能不能不指定插件，直接开扫。

如果git主没打算更新这块，当我没说.....

**Comment by boy-hack** [comment]
原本没有专门设计-u参数的，不过既然说了我觉得加上比较好

**Comment by boy-hack** [comment]
look for https://github.com/boy-hack/w9scan/commit/3ae0f844de91e96386617d0c8450ce365ad038c6

**Comment by d4wner** [comment]
加了-u参数方便多了，不过git主没启用fuzz那些模块让人有点强迫症。
自个儿改的话，是否urlconfig.diyPlugin赋值成LIST_PLUGINS就行，不知道是否有其他复杂依赖？
如果可以直接用的话，git主其实可以提供选项args来指定diyPlugin，这样不用每次去调配置文件。
毕竟git主实在不想加-u下的批量功能的话，有时候想挂VPS批量跑的话，shell脚本循环跑个-u就行了。
感觉理想状态是类似下面这样:

```
 python w9scan.py -u "@1.txt" -diyPlugin "subdomain, find_service, whatcms, fuzz" 
```
当然，git主觉得麻烦当我瞎说...自个儿改主要是pull的时候不方便...

**Comment by boy-hack** [comment]
因为我不太满意`fuzz`插件的功能，所以并没有默认开启，暂时没有想法添加diyPlugin参数，如需要，修改`lib/core/option.py` 121行 ```urlconfig.diyPlugin = ["find_service", "whatcms"]``` 列表加入fuzz即可

**Comment by blackboar** [comment]
应该加一个参数，可以把所有插件来一遍的
