### ISSUE TITLE
报错 无法运行

### ISSUE THREAD

**Issue by i-liberty** [w-digital-scanner/w9scan#29]
**[-] Running plugin error:[Errno 104] Connection reset by peer service:www filename:waf_identify.py
[-] Running plugin error: service:www filename:411.py
[-] Running plugin error: service:www filename:fingeros.py
=
[-] Running plugin error:[Errno 104] Connection reset by peer service:www filename:w9_crossdomain.py
[-] Running plugin error: service:www filename:w9_gitleak.py
Error: [Errno 104] Connection reset by peer
[-] Running plugin error:[Errno 104] Connection reset by peer service:www filename:w9_svncheck.py
=
[-] Running plugin error:global name '_G' is not defined service:mysql filename:w9_mysql_usereme.py
=
报了几个错误之后就卡死了**

**Comment by boy-hack** [comment]
- Connection reset可能由于网站原因导致
- ```Running plugin error:global name '_G' is not defined service:mysql filename:w9_mysql_usereme.py ```已修复，在https://github.com/boy-hack/w9scan/commit/5d57897ff029681bd935774dfa7c91c0362ea1c4
- 卡死问题可打开选项--debug 查看内部运行的插件卡在了哪里

**Comment by i-liberty** [comment]
[DEBUG] load plugin 104.py for service 'ssl'
[DEBUG] load plugin 104.py for service 'ssl'

运行到这里再次卡死跑去看104
104插件检测有问题 第90行    host = arg    //（need string or buffer, tuple found）
但是这也不是导致会一直卡住的原因 怀疑是主程序问题

**Comment by boy-hack** [comment]
@i-liberty 因为内部是有线程池的，默认开启十个线程，一个插件卡住也不会影响其他的运行，可能下列情况
1. 连接网站已经超时了（访问次数过多被ban） 

目前最新=https://github.com/boy-hack/w9scan/commit/811680be46ad42c70f811a15c55ec3fa82c433ee 已经设置了全局超时时间。
如果想确定是否是插件存在问题，可以到`config.conf`将线程设置为1，然后开启--debug选项查询具体原因。

**Comment by boy-hack** [comment]
https://github.com/boy-hack/w9scan/commit/9f9dab0b7df178b98026e943ab76510ca80da47b  新增了扫描后延迟时间，在config.conf中设置，这个应该可以缓解一下
