### ISSUE TITLE
扫描带有端口的地址无法保存文件

### ISSUE THREAD

**Issue by naozibuhao** [w-digital-scanner/w9scan#33]
最后扫描完成以后会生成一个文件 地址_时间.html
如果扫描带有端口的 也会生成一个这样的文件,但是 冒号 : 在文件名中不能存在

**Comment by naozibuhao** [comment]
outhtml.py 中 208行  filename.replace(":","_")
修改为filename = filename.replace(":","_")

**Comment by boy-hack** [comment]
这个问题在之前已经解决了，你用的是哪个版本？

**Comment by boy-hack** [comment]
还是你的冒号是中文的？

**Comment by naozibuhao** [comment]
我从git上直接clone下来的  我的冒号是英文的 
filename.replace(":","") 只是replace了,但是并没有重新赋值给filename
所以filename 还是原来的名字

**Comment by boy-hack** [comment]
sorry,确实是我疏忽了
