### ISSUE TITLE
插件使用问题

### ISSUE THREAD

**Issue by huangtao876** [w-digital-scanner/w9scan#39]
w9scan里的1500+的插件，并不是通用的漏洞类型测试代码（A插件用来测试是否存在SQL注入，B插件用来测试是否存在XSS），这里面的插件都是一些厂商特有的漏洞，比如acsno这个插件是适用于该公司，并不适用其他公司。不知道我理解的对不对。

**Comment by boy-hack** [comment]
正如你的理解，所以w9scan是插件式思想的扫描器，如果是wordpress会调用`wordpress`类型的插件，但是针对网站的通用扫描(WEB识别，IP服务扫描，敏感文件扫描等等)是调用`www`类型插件，爬虫爬去完文件后会调用`spider爬虫类`插件

**Comment by huangtao876** [comment]
> 正如你的理解，所以w9scan是插件式思想的扫描器，如果是的wordpress调用会`wordpress`类型的插件，但是针对网站的通用扫描（WEB识别，IP服务扫描，敏感文件扫描等等）调用的英文`www`类型插件，爬虫完爬去文件后会调用`spider爬虫类`插件

也就是说，如果我只想测试通用的漏洞类型，只需要调用www插件及spider_file插件，且若以后增加其他通用漏洞类型插件，只需要开发并放在spider_file文件夹中，是吗

**Comment by boy-hack** [comment]
> > 正如你的理解，所以w9scan是插件式思想的扫描器，如果是的wordpress调用会`wordpress`类型的插件，但是针对网站的通用扫描（WEB识别，IP服务扫描，敏感文件扫描等等）调用的英文`www`类型插件，爬虫完爬去文件后会调用`spider爬虫类`插件
> 
> 也就是说，如果我只想测试通用的漏洞类型，只需要调用www插件及spider_file插件，且若以后增加其他通用漏洞类型插件，只需要开发并放在spider_file文件夹中，是吗

是的，只需要按照相关格式编写插件会自动加载运行，具体格式可以看看该目录下的其他文件
