### ISSUE TITLE
向导模式启动疑问

### ISSUE THREAD

**Issue by huangtao876** [w-digital-scanner/w9scan#40]
向导模式启动，会让选择插件，请问这边选择插件的意义是什么，是不是选择这四个插件，其他的插件就不会加载？

**Comment by boy-hack** [comment]
默认全部加载，但是这个几个插件加载的耗时会比较长，所以选择性加载，还有，尽量在一个issue中交流，不要开多个issue，issue问题解决后关闭issue

**Comment by huangtao876** [comment]
> 默认全部加载，但是这个几个插件加载的耗时会比较长，所以选择性加载，还有，尽量在一个issue中交流，不要开多个issue，issue问题解决后关闭issue

多谢指导，准备看源码了。

**Comment by huangtao876** [comment]
源码已看完，关闭问题
